### ISSUE TITLE
UX around character limit is suboptimal

### ISSUE THREAD

**Issue by StuartMillsAmtek** [denis-sokolov/chrome-custom-css#14]
Trying to use the custom theme for ChatGPT;
https://github.com/catppuccin/userstyles/tree/main/styles/chatgpt

Adding the theme on both chrome and Edge.
Attempting to add the css content, but it doesn't apply.
Reloading the page after granting permission doesn't result in css update.
going into the extension shows the default "a { color: blue}"

Not sure it's working?

**Comment by StuartMillsAmtek** [comment]
Oh, never mind. In extremely small font it advises of character limit. 
All good, thanks for trying!

**Comment by denis-sokolov** [comment]
Thank you for drawing my attention to it. The character limit was previously enforced, and the fact that it silently did not work is a temporary issue.

Added a big warning now, will show up in the next release.
![image](https://github.com/user-attachments/assets/6480bb5d-26cc-4e13-b4b9-7e60190a5852)
