### ISSUE TITLE
Improve placeholder color

### ISSUE THREAD

**Issue by nirazul** [denis-sokolov/chrome-custom-css#16]
First of all: Thank you for creating this plugin. It scratched an itch (simple editing) I had for a long time!

Would you be open to change the color of the placeholder content? I've tried to delete the content for a minute or so before I realized that this is the placeholder content. I think this could be resolved by using a lighter gray.

(I could also provide a PR, if you want)

**Comment by denis-sokolov** [comment]
That makes sense! It was previously the browser’s native placeholder, but now that we use an editor with syntax highlighting, a better color would be appreciated!
