### ISSUE TITLE
Cloud sync?

### ISSUE THREAD

**Issue by mitranim** [denis-sokolov/chrome-custom-css#8]
Thanks for the extension. It's significantly better than its analogs in the store. The only downside is the lack of cloud sync, which matters when using Chrome on multiple PCs. I'm not that familiar with the Chrome extension API, but I think it may support cloud sync. Any plans to use that?

**Comment by denis-sokolov** [comment]
Good news is this already has cloud sync! If you are logged in to your Chrome, it will synchronize the settings with your Chrome profile. The only inconvenience is Chrome does not sync granted permissions by default, so you have to click on the extension icon once on every website on a new Chrome profile, but once you do it, the styles are synced and applied automatically.

https://github.com/denis-sokolov/chrome-custom-css/blob/70b3b1a8223bdceb2cf691b001546ce636659e9b/src/lib/persist.js#L57

**Comment by mitranim** [comment]
Very nice. I suggest mentioning this in the description.
